### ISSUE TITLE
zoneClean

### ISSUE THREAD

**Issue by itelli** [ioBroker/ioBroker.mihome-vacuum#35]
Hello,

is zoneClean already implemented? i see the information about zoneClean in the readme, but not in the coding?

Many thanks!

**Comment by MeisterTR** [comment]
yes it is implemented
 https://github.com/ioBroker/ioBroker.mihome-vacuum/blob/master/main.js#L125

if you have a s5 you will see the object zoneClean but you have to wirte a json with the coordinates in the object. the right coordinates you only find in the miio log on your robot, therefor you have to root the robot.. or only by try an error..

**Comment by netfaruk** [comment]
@MeisterTR Kardeşim bu zoned cleanup özelliğini v1 de kullanabiliyor muyuz ? 
can I use zoned cleanup function on v1 ?

**Comment by ppent** [comment]
@MeisterTR  I was hoping that I can send the robot via the app to some point on my map and then read that point in the adapter in iobroker. However, the value for GoTo remains empty.
Is the refresh of that value just not implemented in the adapter or is it simply not possible to retrieve the value from the robot?
Would I have a chance to get the value by sending a custom command?

**Comment by MeisterTR** [comment]
It is not possible to read out the current position of the robot. You can get the position by try and error, or with an rooted robot you can take a look in the miio log, there are the commands from the mi app.

**Comment by ppent** [comment]
@MeisterTR Thanks for the clarification.
I identified 4 points on my map now for testing purposes by try and error. However, I'm struggeling to pass those points to the zone clean up. The description of the method seems a bit misleading due to a typo ([X1, y1, x2, x2, count] ==> 3 times x value).
I have the following points for my zone:
upper left: 19500,25800
botton left: 19500,21900
upper right: 22500,25800
button right: 22500,21900

I had no success with the following parameters for zone cleanup (roboter starts zone cleaning and immediately says "finished zone cleaning"):
[19500,25800,22500,21900,1]
[19500,21900,22500,25800,1]
[19500,22500,21900,25800,1]
[22500,25800,19500,21900,1]
[22500,21900,19500,25800,1]

Do you have an advise on how to pass the parameters?

**Comment by dizzle667** [comment]
There is a bug indeed. The ZoneCleanup is not working correctly. You can use "X_Send_command" instead until this bug is fixed. Don't forget the "send own commands" checkbox in your instance settings.
The value should be "app_zoned_clean; [[19500,21900,22500,25800]]" in your case. it is always from bottom left to upper right.
If you want to use multiple zones in one command it would look like this: "app_zoned_clean; [[19500,21900,22500,25800],[19500,25800,21900,28500]]". In this case there will be a second square on top of your first one. I hope that helps :)

**Comment by Apollon77** [comment]
new version published on NPM
